[2025-05-09T16:00:55.990-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-05-09T22:00:45.384646+00:00 [queued]>
[2025-05-09T16:00:55.994-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract manual__2025-05-09T22:00:45.384646+00:00 [queued]>
[2025-05-09T16:00:55.994-0600] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-09T16:00:56.000-0600] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): extract> on 2025-05-09 22:00:45.384646+00:00
[2025-05-09T16:00:56.002-0600] {standard_task_runner.py:60} INFO - Started process 54561 to run task
[2025-05-09T16:00:56.005-0600] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'extract', 'manual__2025-05-09T22:00:45.384646+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/var/folders/r_/0nxm1s0x5f347702p2qydjg80000gn/T/tmpycukl80b']
[2025-05-09T16:00:56.007-0600] {standard_task_runner.py:88} INFO - Job 5: Subtask extract
[2025-05-09T16:00:56.024-0600] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline.extract manual__2025-05-09T22:00:45.384646+00:00 [running]> on host Carloss-MacBook-Pro.local
[2025-05-09T16:00:56.048-0600] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='carlos' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T22:00:45.384646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T22:00:45.384646+00:00'
[2025-05-09T16:00:56.052-0600] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/r_/0nxm1s0x5f347702p2qydjg80000gn/T
[2025-05-09T16:00:56.052-0600] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/scripts/extract.py']
[2025-05-09T16:00:56.058-0600] {subprocess.py:86} INFO - Output:
[2025-05-09T16:00:56.071-0600] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/scripts/extract.py': [Errno 2] No such file or directory
[2025-05-09T16:00:56.072-0600] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-09T16:00:56.075-0600] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/crobles18/Downloads/fire_incidents_pipeline/airflow/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/crobles18/Downloads/fire_incidents_pipeline/airflow/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-09T16:00:56.077-0600] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=extract, execution_date=20250509T220045, start_date=20250509T220055, end_date=20250509T220056
[2025-05-09T16:00:56.081-0600] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task extract (Bash command failed. The command returned a non-zero exit code 2.; 54561)
[2025-05-09T16:00:56.111-0600] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-09T16:00:56.121-0600] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
